### ISSUE TITLE
How does this package work?

### ISSUE THREAD

**Issue by smedi08** [piotrmus/akeneo-product-translation#1]
I have installed this package but I don't see how the translation is done, and nothing new appears when I click on the bulk edit action.
You can help?

**Comment by piotrmus** [comment]
@smedi08 Have you rebuild your fornt after package installation?

**Comment by smedi08** [comment]
I think so, I have run the following commands:

./console pim: install: assets

./console assets: install --symlink

./console cache: clear --env = prod

Do you need to do something else?

It is a test machine, if you want to look at something I can leave you the root user.

**Comment by piotrmus** [comment]
If you run Akeneo 4 run `make front` or if you run Akeneo 5 `make upgrade-front` this commands will build your front.

**Comment by smedi08** [comment]
I have not installed with docker, I have the installation with the bitnami stack.

The result of the command

root@akeneo-v5:/opt/akeneo-5.0.24-0/apps/akeneo/htdocs#  make upgrade-front
make node_modules
make[1]: Entering directory '/opt/akeneo-5.0.24-0/apps/akeneo/htdocs'
make[1]: 'node_modules' is up to date.
make[1]: Leaving directory '/opt/akeneo-5.0.24-0/apps/akeneo/htdocs'
make cache
make[1]: Entering directory '/opt/akeneo-5.0.24-0/apps/akeneo/htdocs'
docker-compose run -u www-data --rm php rm -rf var/cache && docker-compose run -u www-data --rm php php bin/console cache:warmup
/bin/sh: 1: docker-compose: not found
make[1]: *** [Makefile:61: cache] Error 127
make[1]: Leaving directory '/opt/akeneo-5.0.24-0/apps/akeneo/htdocs'
make: *** [Makefile:121: upgrade-front] Error 2

**Comment by smedi08** [comment]
HI, any sugestion for this topic?
