### ISSUE TITLE
Error after doing a cache:clear

### ISSUE THREAD

**Issue by aelachar** [piotrmus/akeneo-product-translation#2]
Hello @piotrmus ,

After updating the extension from 0.1.9 to 0.1.10, I got the following error during a clear:cache
Version Akeneo 5.0.57 CE
The error message:
```BASH
In CheckExceptionOnInvalidReferenceBehaviorPass.php line 86:

  The service "Piotrmus\Translator\Connector\Processor\MassEdit\TranslateAttributesProcessor" has a dependency on a non-existent service "pim_catalog.updater.entity_with_values_property_setter_without_permission".
```

Can you help? Thank you

**Comment by piotrmus** [comment]
Hi @aelachar 

There was a bug with community version compatibility. `pim_catalog.updater.entity_with_values_property_setter_without_permission` is only in EE. I will probably need to create a new release branch for Enterprise version.

I will release 0.1.11 version with fix for that.
