### ISSUE TITLE
getting dependency error after installing

### ISSUE THREAD

**Issue by Andi757** [piotrmus/akeneo-product-translation#3]
Hey, 
I am getting an dependency error after installing the extension.
Steps to reproduce:
`composer require piotrmus/akeneo-product-translation`
added `\Piotrmus\Translator\PiotrmusTranslatorBundle::class => ['dev' => true, 'test' => true, 'prod' => true],` to bunles.php
added `bin/console akeneo:batch:create-job internal update_product_translations mass_edit update_product_translations '{}' 'Translate product'`
then I wanted to rebuild the frontend. Typed 
`bin/console cache:clear` 
but got an error:
`The service "piotrmus.step.update_product_translations.mass_edit" has a dependency on a non-existent service "akeneo_batch.job.job_stopper".`

It's weird, because akeneo also uses this dependency.

Akeneo Version 4.0.124
Piotrmus Version 0.1.10

can you help me out?

**Comment by piotrmus** [comment]
Hi @Andi757 

There was a bug with 4.x compatibility. `keneo_batch.job.job_stopper` is only in 5.x version. I will probably need to create a new release branch for Enterprise version.

I will release 0.1.11 version with fix for that.
