### ISSUE TITLE
Could not find a matching version of package.

### ISSUE THREAD

**Issue by Andi757** [piotrmus/akeneo-product-translation#4]
Hi,
I was trying to install your package but I get the following error when requiring it
Command
`composer require macopedia/akeneo-product-translation`
Error
`Could not find a matching version of package macopedia/akeneo-product-translation. Check the package spelling, your version constraint and that the package is available in a stability which matche
  s your minimum-stability (stable).`

**Comment by piotrmus** [comment]
Hi @Andi757 ,

This seems to look like you have a problem with composer requirements definition. Please, paste your `composej.json` file here to check how you define this.
