### ISSUE TITLE
Error on adding job instance : job not registered

### ISSUE THREAD

**Issue by JohanFactory** [piotrmus/akeneo-product-translation#5]
Hey there,

Install went fine, but it's impossible to add a job instance:

`11:54:27 CRITICAL  [console] Error thrown while running command "akeneo:batch:create-job internal update_product_translations mass_edit update_product_translations '{}' 'Translate product'". Message: "The job "update_product_translations" is not registered" ["exception" => Akeneo\Tool\Component\Batch\Job\UndefinedJobException^ { …},"command" => "akeneo:batch:create-job internal update_product_translations mass_edit update_product_translations '{}' 'Translate product'","message" => "The job "update_product_translations" is not registered"]`

As a consequence, when trying to confirm a translation to make, it triggers an error 500 on /rest/mass_edit, and the exact error in logs is: 

`[2023-01-24 15:10:59] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Translation\Exception\NotFoundResourceException: "No JobInstance found with code "update_product_translations"" at /pim-community-standard/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Enrichment/Bundle/MassEditAction/OperationJobLauncher.php line 59 {"exception":"[object] (Symfony\\Component\\Translation\\Exception\\NotFoundResourceException(code: 0): No JobInstance found with code \"update_product_translations\" at /pim-community-standard/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Enrichment/Bundle/MassEditAction/OperationJobLauncher.php:59)"} []`

Using Akeneo CE 6.0.61.

Any chance to get an update on this ?

Thanks.

**Comment by JohanFactory** [comment]
Bypassed by adding manually the job instance.

`INSERT INTO `akeneo_batch_job_instance` (`id`, `code`, `label`, `job_name`, `status`, `connector`, `raw_parameters`, `type`) VALUES (NULL, 'update_product_translations', 'Translate product', 'update_product_translations', '0', 'internal', 'a:0:{}', 'mass_edit');`

**Comment by piotrmus** [comment]
Hi Johan,

In `README.md` file you can find a description how to install this plugin. There is information that you need run the command to create a job instance.

```bash
bin/console akeneo:batch:create-job internal update_product_translations mass_edit update_product_translations '{}' 'Translate product'
```

This command do basically that same as your SQL query.

**Comment by JohanFactory** [comment]
Hi !

The first error I quote is the result of this very command, sorry to have been unclear about that.

So, doing that 

`bin/console akeneo:batch:create-job internal update_product_translations mass_edit update_product_translations '{}' 'Translate product'`

fails with this error 

`11:54:27 CRITICAL  [console] Error thrown while running command "akeneo:batch:create-job internal update_product_translations mass_edit update_product_translations '{}' 'Translate product'". Message: "The job "update_product_translations" is not registered" ["exception" => Akeneo\Tool\Component\Batch\Job\UndefinedJobException^ { …},"command" => "akeneo:batch:create-job internal update_product_translations mass_edit update_product_translations '{}' 'Translate product'","message" => "The job "update_product_translations" is not registered"]`

**Comment by piotrmus** [comment]
Cannot reproduce
